IslamSandhesham/Models/Sections.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace IslamSandhesham.Models
{
    public class Sections
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }
        public int SectionId { get; set; }
        public string Description { get; set; }
        public string ClassName { get; set; }
        public int? Type { get; set; }
    }
}

IslamSandhesham/Controllers/SectionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IslamSandhesham.Models;

namespace IslamSandhesham.Controllers
{
    public class SectionsController : Controller
    {
        private MyContext db = new MyContext();

        // GET: Sections
        public ActionResult Index( )
        {
            bool res =isLoggedIn();
            if (res)
            {
                ViewBag.Type = 1;
                return View(db.Sections.Where(w=>w.Type==1).ToList()); //by default it returns button sections
            }
            else
            {
                return RedirectToAction("Admin","Home", new { isLogin = false });
            }
        }
        public ActionResult ImageSections()
        {
            ViewBag.Type = 2;
            return View("Index", db.Sections.Where(w => w.Type == 2).ToList());
            // return View(db.Sections.Where(w => w.Type == 2).ToList()); //by default it returns button sections
        }
        public bool isLoggedIn()
        {
            Admin admin = db.Admin.OrderBy(w => w.id).FirstOrDefault();
            bool isLoggedIn = false;
            isLoggedIn = admin.IsLoggedIn;
            if (isLoggedIn)
            {
                TimeSpan ts = DateTime.Now - (DateTime)admin.LastLoginTime;
                if (ts.Days > 1 || ts.Hours > 1 || ts.Minutes > 45)
                {
                    isLoggedIn = false;
                    admin.IsLoggedIn = false;
                    db.SaveChanges();
                }
            }
            return isLoggedIn;
        }

        // GET: Sections/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sections sections = db.Sections.Find(id);
            if (sections == null)
            {
                return HttpNotFound();
            }
            return View(sections);
        }

        // GET: Sections/Create
        public ActionResult Create()
        {
            bool res = isLoggedIn();
            if (res)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Admin", "Home", new { isLogin = false });
            }
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,SectionId,Description,ClassName,Type")] Sections sections)
        {
            bool res = isLoggedIn();
            if (res)
            {
                if (ModelState.IsValid)
                {
                    db.Sections.Add(sections);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View(sections);
            }
            else
            {
                return RedirectToAction("Admin", "Home", new { isLogin = false });
            }
            
        }

        // GET: Sections/Edit/5
        public ActionResult Edit(int? id)
        {
           
            bool res = isLoggedIn();
            if (res)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Sections sections = db.Sections.Find(id);
                if (sections == null)
                {
                    return HttpNotFound();
                }
                return View(sections);
            }
            else
            {
                return RedirectToAction("Admin", "Home", new { isLogin = false });
            }
        }

        // POST: Sections/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,SectionId,Description,ClassName,Type")] Sections sections)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sections).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sections);
        }

        // GET: Sections/Delete/5
        public ActionResult Delete(int? id)
        {
            bool res = isLoggedIn();
            if (res)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Sections sections = db.Sections.Find(id);
                if (sections == null)
                {
                    return HttpNotFound();
                }
                return View(sections);
            }
            else
            {
                return RedirectToAction("Admin", "Home", new { isLogin = false });
            }            

        }

        // POST: Sections/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sections sections = db.Sections.Find(id);
            db.Sections.Remove(sections);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IslamSandhesham/Views/Sections/Create.cshtml
@model IslamSandhesham.Models.Sections

@{
    ViewBag.Title = "Create";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Create Section</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
      

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>*@
        <div class="form-group">
            @{
                var list = new SelectList(new[]
                    {
            new {ID="1", Name="Section For Buttons"},
            new {ID="2", Name="Section For Image"},
        },
                    "ID", "Name", 1);
            }
            @Html.DropDownList("Type", list, new { @class = "form-control ml-3" })
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-info " />
            </div>
        </div>
    </div>
}

<div>
    <button class="btn btn-warning ml-3" onclick="location.href='@Url.Action("Index", "Sections")';return false;">Back to Sections</button>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $("#SectionId").change(function () {
           // alert();
        });
        $(document).ready(function () {
            $("#loader").hide();
        });
    </script>
}

IslamSandhesham/Views/Sections/Delete.cshtml
@model IslamSandhesham.Models.Sections

@{
    ViewBag.Title = "Delete";
}


<h3 class="text-danger">Are you sure you want to delete this?</h3>
<hr />
<div class="border border-info">

    <dl class="dl-horizontal m-4">
        <dt>
            @Html.DisplayNameFor(model => model.SectionId) :  @Html.DisplayFor(model => model.SectionId)
        </dt>

        <dt>
            @Html.DisplayNameFor(model => model.Description) : @Html.DisplayFor(model => model.Description)
        </dt>

        <dt>
            @Html.DisplayNameFor(model => model.ClassName) :  @Html.DisplayFor(model => model.ClassName)
        </dt>

        <dt>
            @Html.DisplayNameFor(model => model.Type) :  @Html.DisplayFor(model => model.Type)
        </dt>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color m-4">
            <input type="submit" value="Delete" class="btn btn-danger" />
            <button class="btn btn-warning ml-3" onclick="location.href='@Url.Action("Index", "Sections")';return false;">Back to Sections</button>
        </div>
    }
</div>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#loader").hide();
    });
</script>

IslamSandhesham/Views/Sections/Details.cshtml
@model IslamSandhesham.Models.Sections

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Sections</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SectionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SectionId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClassName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClassName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IslamSandhesham/Views/Sections/Edit.cshtml
@model IslamSandhesham.Models.Sections

@{
    ViewBag.Title = "Edit";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Edit Section</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.SectionId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SectionId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SectionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClassName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClassName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClassName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @{
                var list = new SelectList(new[]
                    {
            new {ID="1", Name="Section For Buttons"},
            new {ID="2", Name="Section For Image"},
        },
                    "ID", "Name", 1);
            }
            @Html.DropDownList("Type", list, new { @class = "form-control ml-3" })
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    <button class="btn btn-warning ml-3" onclick="location.href='@Url.Action("Index", "Sections")';return false;">Back to Sections</button>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#loader").hide();
    });
</script>

IslamSandhesham/Views/Sections/ImageSections.cshtml
@model IEnumerable<IslamSandhesham.Models.Sections>

@{
    ViewBag.Title = "Index";
}

<h2>Sections</h2>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@

<div class="row">
    <button class="btn btn-info" onclick="location.href='@Url.Action("Create", "Sections")';return false;">Create New</button>
    <div class="form-group">
        @{
            var list = new SelectList(new[]
                {
        new {ID="1", Name="Buttons Sections"},
        new {ID="2", Name="Images Sections"},
    },
                "ID", "Name", 1);
        }
        @Html.DropDownList("Type2", list, new { @class = "form-control ml-3" })
    </div>

</div>
<div class="border border-info mt-5">
    <table class="table table-bordered table-hover table-striped w-100 bg-light">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SectionId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ClassName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SectionId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ClassName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.id })*@
                    <button class="btn btn-primary btn-sm" onclick="location.href='@Url.Action("Edit", "Sections")/?id=@item.id';return false;">Edit</button>
                    <button class="btn btn-danger btn-sm" onclick="location.href='@Url.Action("Delete", "Sections")?id=@item.id';return false;">Delete</button>
                </td>
            </tr>
        }

    </table>
</div>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#loader").hide();
    });

    $("#Type2").change(function () {
       //var id = $("#Type2").val(); 
        window.location.href = '/Sections/Index';      //'/Home/Info/?id='+ id;
    });
</script>

IslamSandhesham/Views/Sections/Index.cshtml
@model IEnumerable<IslamSandhesham.Models.Sections>

@{
    ViewBag.Title = "Index";
    var type = ViewBag.Type;
}

<h2>Sections</h2>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<div class="row">
    <button class="btn btn-info" onclick="location.href='@Url.Action("Create", "Sections")';return false;">Create New</button>
    <div class="form-group">
        @{
            var list = new SelectList(new[]
                {
                new {ID="0", Name="--Select--"},
        new {ID="1", Name="Buttons Sections"},
        new {ID="2", Name="Images Sections"},
    },
                "ID", "Name", type);
        }
        @Html.DropDownList("Type2", list, new { @class = "form-control ml-3" })
    </div>

</div>

 <div class="border border-info mt-5">
    <table class="table table-bordered table-hover table-striped w-100 bg-light">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SectionId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ClassName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SectionId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ClassName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.id })*@
                    <button class="btn btn-primary btn-sm" onclick="location.href='@Url.Action("Edit", "Sections")/?id=@item.id';return false;">Edit</button>
                    <button class="btn btn-danger btn-sm" onclick="location.href='@Url.Action("Delete", "Sections")?id=@item.id';return false;">Delete</button>
                </td>
            </tr>
        }

    </table>
</div>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#loader").hide();
    });

    $("#Type2").change(function () {
        var id = $("#Type2").val(); 
        if (id == 2) {
            window.location.href = '/Sections/ImageSections';      //'/Home/Info/?id='+ id;
        }
        else if(id == 1) {
            window.location.href = '/Sections/Index';
        }
        
    });
</script>