IslamSandhesham/Controllers/TodayHadithVersesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IslamSandhesham.Models;

namespace IslamSandhesham.Controllers
{
    public class TodayHadithVersesController : Controller
    {
        private MyContext db = new MyContext();

        // GET: TodayHadithVerses
        public ActionResult Index()
        {
            return View(db.TodayHadithVerses.ToList());
        }
        public ActionResult ViewAll()
        {
            return View(db.TodayHadithVerses.ToList());
        }
        // GET: TodayHadithVerses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TodayHadithVerse todayHadithVerse = db.TodayHadithVerses.Find(id);
            if (todayHadithVerse == null)
            {
                return HttpNotFound();
            }
            return View(todayHadithVerse);
        }

        // GET: TodayHadithVerses/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TodayHadithVerses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Type,Reference,ArabicText,TeluguText,EnglishText,CreatedDate,UpdatedDate")] TodayHadithVerse todayHadithVerse)
        {
            if (ModelState.IsValid)
            {
                todayHadithVerse.CreatedDate = DateTime.Now;
                db.TodayHadithVerses.Add(todayHadithVerse);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(todayHadithVerse);
        }

        // GET: TodayHadithVerses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TodayHadithVerse todayHadithVerse = db.TodayHadithVerses.Find(id);
            if (todayHadithVerse == null)
            {
                return HttpNotFound();
            }
            return View(todayHadithVerse);
        }

        // POST: TodayHadithVerses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Type,Reference,ArabicText,TeluguText,EnglishText,CreatedDate,UpdatedDate")] TodayHadithVerse todayHadithVerse)
        {
            if (ModelState.IsValid)
            {
                todayHadithVerse.UpdatedDate = DateTime.Now;
                db.Entry(todayHadithVerse).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(todayHadithVerse);
        }

        // GET: TodayHadithVerses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TodayHadithVerse todayHadithVerse = db.TodayHadithVerses.Find(id);
            if (todayHadithVerse == null)
            {
                return HttpNotFound();
            }
            return View(todayHadithVerse);
        }

        // POST: TodayHadithVerses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TodayHadithVerse todayHadithVerse = db.TodayHadithVerses.Find(id);
            db.TodayHadithVerses.Remove(todayHadithVerse);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IslamSandhesham/Views/TodayHadithVerses/Create.cshtml
@using IslamSandhesham.Models

@model TodayHadithVerse

@{
    ViewBag.Title = "Create";
}

<h2 class="mt-5">Create Today Hadith & Verse</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="col-12">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })            
            @{
                    var list = new SelectList(new[]
                        {
            new {ID="1", Name="Hadith"},
            new {ID="2", Name="Quran"},           
        },
                        "ID", "Name", 1);
                }
                @Html.DropDownList("Type", list, new { @class = "form-control ml-3" })           
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Reference, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Reference, new { htmlAttributes = new { @class = "form-control col-12 col-md-9" } })
                @Html.ValidationMessageFor(model => model.Reference, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArabicText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.ArabicText, 5, 500, new { @class = "form-control  col-12 col-md-9" })
                @Html.ValidationMessageFor(model => model.ArabicText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeluguText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.TeluguText, 5, 500, new { @class = "form-control  col-12 col-md-9" })
                @Html.ValidationMessageFor(model => model.TeluguText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EnglishText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.EnglishText, 5, 500, new { @class = "form-control col-12 col-md-9" })
                @Html.ValidationMessageFor(model => model.EnglishText, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}


<button class="btn btn-info" onclick="location.href='@Url.Action("Index", "TodayHadithVerses")';return false;">Back to List</button>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#loader").hide();
    });
</script>

IslamSandhesham/Views/TodayHadithVerses/Delete.cshtml
@model IslamSandhesham.Models.TodayHadithVerse

@{
    ViewBag.Title = "Delete";
}


<h3>Are you sure you want to delete this?</h3>
<hr/>
<div>
   
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reference)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reference)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ArabicText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArabicText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TeluguText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeluguText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EnglishText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EnglishText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-success" /> |
            <button class="btn btn-info" onclick="location.href='@Url.Action("Index", "TodayHadithVerses")';return false;">Back to List</button>
        </div>
    }
</div>

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#loader").hide();
    });
</script>

IslamSandhesham/Views/TodayHadithVerses/Details.cshtml
@model IslamSandhesham.Models.TodayHadithVerse

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TodayHadithVerse</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reference)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reference)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ArabicText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArabicText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TeluguText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeluguText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EnglishText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EnglishText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IslamSandhesham/Views/TodayHadithVerses/Edit.cshtml
@model IslamSandhesham.Models.TodayHadithVerse

@{
    ViewBag.Title = "Edit";
}

<h2 class="mt-5">Edit Today Hadith & Verse</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @{
                var list = new SelectList(new[]
                    {
                new {ID="1", Name="Hadith"},
                new {ID="2", Name="Quran"},
            },
                    "ID", "Name", 1);
            }
            @Html.DropDownList("Type", list, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Reference, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Reference, new { htmlAttributes = new { @class = "form-control col-12 col-md-9" } })
            @Html.ValidationMessageFor(model => model.Reference, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ArabicText, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.ArabicText, 5, 500, new { @class = "form-control col-12 col-md-9" })
            @Html.ValidationMessageFor(model => model.ArabicText, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TeluguText, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.TeluguText, 5, 500, new { @class = "form-control  col-12 col-md-9" })
            @Html.ValidationMessageFor(model => model.TeluguText, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EnglishText, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.EnglishText, 5, 500, new { @class = "form-control  col-12 col-md-9" })
            @Html.ValidationMessageFor(model => model.EnglishText, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group d-none">
        @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CreatedDate, new { @class = "form-control  col-12 col-md-9" })
            @Html.ValidationMessageFor(model => model.EnglishText, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-success" />
        </div>
    </div>
</div>
}

<button class="btn btn-info" onclick="location.href='@Url.Action("Index", "TodayHadithVerses")';return false;">Back to List</button>
      

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#loader").hide();
        //alert($("#CreatedDate").val());
        var date = $("#CreatedDate").val();
        $("#CreatedDate").val(date);
    });
</script>

IslamSandhesham/Views/TodayHadithVerses/Index.cshtml
@model IEnumerable<IslamSandhesham.Models.TodayHadithVerse>

@{
    ViewBag.Title = "Index";
}

<h2  class="my-4">Today Hadith and Verses</h2>


<button class="btn btn-info my-2" onclick="location.href='@Url.Action("Create", "TodayHadithVerses")';return false;">Create New</button>
<table class="table table-bordered table-hover table-striped text-dark bg-light">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Reference)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ArabicText)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TeluguText)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EnglishText)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>       
        <th>Action</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @if (item.Type == 1)
                {
                    <span>Hadith</span>
                }
                else if (item.Type == 2)
                {
                    <span>Quran</span>
                }
                
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Reference)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ArabicText)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TeluguText)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EnglishText)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>           
            <td>
                <button class="btn btn-primary btn-sm" onclick="location.href='@Url.Action("Edit", "TodayHadithVerses")/?id=@item.Id';return false;">Edit</button>
                <button class="btn btn-danger btn-sm" onclick="location.href='@Url.Action("Delete", "TodayHadithVerses")?id=@item.Id';return false;">Delete</button>

            </td>
        </tr>
    }

</table>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#loader").hide();
    }); 
    </script>

IslamSandhesham/Views/TodayHadithVerses/ViewAll.cshtml
@model IEnumerable<IslamSandhesham.Models.TodayHadithVerse>

@{
    ViewBag.Title = "ViewAll";
}

<section class="p-0 border-0 mt-5">
    <div class="row">
        <div class="col-md-6 mb-5">
            @foreach (var item in Model.Where(w => w.Type == 1))
            {
                <div  style="" class="mt-5">
                    @*<h4 class="text-secondary">Selected <span style="color:#AE52FF;">Hadith</span></h4>*@
                    <div class="card h-100 m-0" style="border-top: 5px solid #AE52FF !important;
        background-image: url('../../Content/images/bg-banner-2.png');
        background-repeat: no-repeat;
        background-position: center top;
        background-size: 100% 70%;">
                        <div class="card-body" style="height: 500px !important; overflow-y: scroll;">
                            <h4 class="text-secondary text-center mb-5" style="font-family: 'Strait', sans-serif;"> <span style="color:#AE52FF;">Hadith</span></h4>
                            <h6 class="mb-4" style="font-family: 'Strait', sans-serif;">@item.Reference</h6>
                            <h3 class="font-arabic2 text-center read-more mb-3" data-char="250" style="font-family: 'Lateef', cursive;">
                                @item.ArabicText
                            </h3>
                            <h5 class="font-urdu text-center read-more mb-3" style="font-family: 'Sree Krushnadevaraya', serif;">
                                @item.TeluguText
                            </h5>
                            <h6 class="text-center m-0 read-more mb-3" data-char="200" style="font-family: 'Strait', sans-serif;">
                                @item.EnglishText
                            </h6>
                        </div>
                        <div class="card-footer bg-white text-right">
                        </div>
                    </div>
                </div><div class="col-md-6 mb-5">

                </div>
            }
        </div>

        <div class="col-md-6 mb-5">
            @foreach (var item1 in Model.Where(w => w.Type == 2))
            {
                <div style="" class="mt-5" >
                    @*<h4 class="text-secondary">Selected <span style="color:#52d3a4">Verse</span></h4>*@
                    <div class="card h-100 m-0" style="border-top:5px solid #52d3a4 !important;
        background-image: url('../../Content/images/bg-banner-2.png'); background-repeat:no-repeat; background-position:center top; background-size:100% 70%;">
                        <div class="card-body" style="height: 500px !important; overflow-y: scroll;">
                            <h4 class="text-secondary text-center mb-5" style="font-family: 'Strait', sans-serif;"> <span style="color:#52d3a4">Verse</span></h4>
                            <h6 class="mb-4" style="font-family: 'Strait', sans-serif;"> @item1.Reference</h6>
                            <h5 class="font-arabic text-center read-more mb-3" data-char="250" style="font-family: 'Lateef', cursive;font-size:25px">@item1.ArabicText</h5>
                            <h5 class="font-urdu text-center read-more mb-3" data-char="200" style="font-family: 'Sree Krushnadevaraya', serif;">@item1.TeluguText</h5>
                            <h6 class="text-center m-0 read-more mb-3" data-char="200" style="font-family: 'Strait', sans-serif;">@item1.EnglishText</h6>
                        </div>
                        <div class="card-footer bg-white text-right">
                            
                        </div>
                    </div>
                </div>   <div class="col-md-6 mb-5">

</div>   }
        </div>

    </div>

</section>


<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#loader").hide();
    });
</script>